services:
  db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - ministack
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3001
    depends_on:
      - server
    ports:
      - "8080:80"
    restart: unless-stopped

  deployer:
    build:
      context: ./deployer
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - ministack
    volumes:
      - ./deployer:/app
      - tofu-deploy:/tofu-deploy
    ports:
      - "8002:8002"
    restart: unless-stopped

  # AWS Emulator.
  ministack:
    image: ministackorg/ministack
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  stackport:
    image: davireis/stackport:latest
    ports:
      - "8082:8080"
    environment:
      - AWS_ENDPOINT_URL=http://ministack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mock-access-key
      - AWS_SECRET_ACCESS_KEY=mock-secret-key
    depends_on:
      - ministack
    restart: unless-stopped

volumes:
  tofu-deploy:
