# Generated by Django 4.2.17 on 2026-05-22 13:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("nodes", models.JSONField(blank=True, default=list)),
                ("edges", models.JSONField(blank=True, default=list)),
                ("deployment_settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-updated_at"],
            },
        ),
    ]
