# Generated by Django 5.1.4 on 2026-05-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="project",
            table=None,
        ),
    ]
