# Generated by Django 5.1.4 on 2026-09-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_llmconfig"),
        ("projects", "0002_project_aws_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="llm_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="organisations.llmconfig",
            ),
        ),
    ]
