# Generated by Django 5.1.4 on 2026-06-08 20:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("access_key_id", models.CharField(max_length=255)),
                ("secret_access_key", models.CharField(max_length=255)),
                (
                    "endpoint_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aws_accounts",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "aws_accounts",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("organisation", "name")},
            },
        ),
    ]
