# Generated by Django 5.1.4 on 2026-09-09 11:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_awsaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "ANTHROPIC"),
                            ("gemini", "GEMINI"),
                            ("ollama", "OLLAMA"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("api_key", models.CharField(blank=True, default="", max_length=512)),
                ("base_url", models.CharField(blank=True, default="", max_length=512)),
                ("context_window", models.PositiveIntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_configs",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "llm_configs",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("organisation", "name")},
            },
        ),
    ]
