# Generated by Django 5.1.4 on 2026-06-16 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_aws_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('archived', 'ARCHIVED')], default='active', max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to='projects.project')),
            ],
            options={
                'db_table': 'agent_conversations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'USER'), ('assistant', 'ASSISTANT'), ('tool', 'TOOL')], max_length=10)),
                ('content', models.JSONField(default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentconversation')),
            ],
            options={
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('awaiting_client', 'AWAITING_CLIENT'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='running', max_length=16)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agent.agentconversation')),
            ],
            options={
                'db_table': 'agent_runs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
