# Generated by Django 5.1.4 on 2026-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='catalog',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
