# Generated by Django 5.1.4 on 2026-09-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_agentrun_resolved_results_alter_agentrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmessage",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="agent.agentrun",
            ),
        ),
    ]
