# Generated by Django 5.1.4 on 2026-06-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="archived",
        ),
        migrations.AlterField(
            model_name="annotationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "CREATED"),
                    ("resolved", "RESOLVED"),
                    ("reopened", "REOPENED"),
                    ("moved", "MOVED"),
                    ("comment_added", "COMMENT_ADDED"),
                    ("comment_deleted", "COMMENT_DELETED"),
                ],
                max_length=20,
            ),
        ),
    ]
