# Generated by Django 5.1.4 on 2026-05-31 22:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_alter_project_options_alter_project_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("invoking", "Invoking"),
                            ("in_progress", "In Progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "graph_snapshot",
                    models.JSONField(
                        help_text="Full nodes + edges + settings at deploy time."
                    ),
                ),
                (
                    "tofu_config",
                    models.JSONField(
                        blank=True,
                        help_text="The .tf.json sent to the deployer.",
                        null=True,
                    ),
                ),
                (
                    "tofu_state",
                    models.JSONField(
                        blank=True,
                        help_text="OpenTofu state file contents after apply.",
                        null=True,
                    ),
                ),
                (
                    "tofu_plan_output",
                    models.TextField(
                        blank=True, default="", help_text="Human-readable plan output."
                    ),
                ),
                ("logs", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_deployment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDeploymentState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tofu_state", models.JSONField(blank=True, null=True)),
                (
                    "deployed_graph_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="deployments.deployment",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_state",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_project_deployment_state",
            },
        ),
        migrations.CreateModel(
            name="DeployedResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node_id",
                    models.CharField(help_text="Canvas node ID.", max_length=255),
                ),
                (
                    "service_id",
                    models.CharField(help_text="e.g. 'lambda'.", max_length=100),
                ),
                (
                    "resource_identifier",
                    models.CharField(
                        help_text="e.g. ARN or resource name.", max_length=500
                    ),
                ),
                ("config_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "deployment_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="deployments.projectdeploymentstate",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_deployed_resource",
            },
        ),
    ]
